code=./objects/roadside/roadside.asm
sprite.Img_Roadside_80_L0=./objects/roadside/image/Img_Roadside_80_L0.png;ND0,ND1
sprite.Img_Roadside_80_L1=./objects/roadside/image/Img_Roadside_80_L1.png;ND0,ND1
sprite.Img_Roadside_80_L2=./objects/roadside/image/Img_Roadside_80_L2.png;ND0,ND1
sprite.Img_Roadside_80_L3=./objects/roadside/image/Img_Roadside_80_L3.png;ND0,ND1
sprite.Img_Roadside_80_L4=./objects/roadside/image/Img_Roadside_80_L4.png;ND0,ND1
sprite.Img_Roadside_80_L5=./objects/roadside/image/Img_Roadside_80_L5.png;ND0,ND1
sprite.Img_Roadside_80_L6=./objects/roadside/image/Img_Roadside_80_L6.png;ND0,ND1
sprite.Img_Roadside_80_L7=./objects/roadside/image/Img_Roadside_80_L7.png;ND0,ND1
sprite.Img_Roadside_81_L0=./objects/roadside/image/Img_Roadside_81_L0.png;ND0,ND1
sprite.Img_Roadside_81_L1=./objects/roadside/image/Img_Roadside_81_L1.png;ND0,ND1
sprite.Img_Roadside_81_L2=./objects/roadside/image/Img_Roadside_81_L2.png;ND0,ND1
sprite.Img_Roadside_81_L3=./objects/roadside/image/Img_Roadside_81_L3.png;ND0,ND1
sprite.Img_Roadside_81_L4=./objects/roadside/image/Img_Roadside_81_L4.png;ND0,ND1
sprite.Img_Roadside_81_L5=./objects/roadside/image/Img_Roadside_81_L5.png;ND0,ND1
sprite.Img_Roadside_81_L6=./objects/roadside/image/Img_Roadside_81_L6.png;ND0,ND1
sprite.Img_Roadside_81_L7=./objects/roadside/image/Img_Roadside_81_L7.png;ND0,ND1
sprite.Img_Roadside_83_L0=./objects/roadside/image/Img_Roadside_83_L0.png;ND0,ND1
sprite.Img_Roadside_83_L1=./objects/roadside/image/Img_Roadside_83_L1.png;ND0,ND1
sprite.Img_Roadside_83_L2=./objects/roadside/image/Img_Roadside_83_L2.png;ND0,ND1
sprite.Img_Roadside_83_L3=./objects/roadside/image/Img_Roadside_83_L3.png;ND0,ND1
sprite.Img_Roadside_83_L4=./objects/roadside/image/Img_Roadside_83_L4.png;ND0,ND1
sprite.Img_Roadside_83_L5=./objects/roadside/image/Img_Roadside_83_L5.png;ND0,ND1
sprite.Img_Roadside_83_L6=./objects/roadside/image/Img_Roadside_83_L6.png;ND0,ND1
sprite.Img_Roadside_83_L7=./objects/roadside/image/Img_Roadside_83_L7.png;ND0,ND1
sprite.Img_Roadside_87_L0=./objects/roadside/image/Img_Roadside_87_L0.png;ND0,ND1
sprite.Img_Roadside_87_L1=./objects/roadside/image/Img_Roadside_87_L1.png;ND0,ND1
sprite.Img_Roadside_87_L2=./objects/roadside/image/Img_Roadside_87_L2.png;ND0,ND1
sprite.Img_Roadside_87_L3=./objects/roadside/image/Img_Roadside_87_L3.png;ND0,ND1
sprite.Img_Roadside_87_L4=./objects/roadside/image/Img_Roadside_87_L4.png;ND0,ND1
sprite.Img_Roadside_87_L5=./objects/roadside/image/Img_Roadside_87_L5.png;ND0,ND1
sprite.Img_Roadside_87_L6=./objects/roadside/image/Img_Roadside_87_L6.png;ND0,ND1
sprite.Img_Roadside_87_L7=./objects/roadside/image/Img_Roadside_87_L7.png;ND0,ND1
sprite.Img_Roadside_8F_L0=./objects/roadside/image/Img_Roadside_8F_L0.png;ND0,ND1
sprite.Img_Roadside_8F_L1=./objects/roadside/image/Img_Roadside_8F_L1.png;ND0,ND1
sprite.Img_Roadside_8F_L2=./objects/roadside/image/Img_Roadside_8F_L2.png;ND0,ND1
sprite.Img_Roadside_8F_L3=./objects/roadside/image/Img_Roadside_8F_L3.png;ND0,ND1
sprite.Img_Roadside_8F_L4=./objects/roadside/image/Img_Roadside_8F_L4.png;ND0,ND1
sprite.Img_Roadside_8F_L5=./objects/roadside/image/Img_Roadside_8F_L5.png;ND0,ND1
sprite.Img_Roadside_8F_L6=./objects/roadside/image/Img_Roadside_8F_L6.png;ND0,ND1
sprite.Img_Roadside_8F_L7=./objects/roadside/image/Img_Roadside_8F_L7.png;ND0,ND1
sprite.Img_Roadside_90_L0=./objects/roadside/image/Img_Roadside_90_L0.png;ND0,ND1
sprite.Img_Roadside_90_L1=./objects/roadside/image/Img_Roadside_90_L1.png;ND0,ND1
sprite.Img_Roadside_90_L2=./objects/roadside/image/Img_Roadside_90_L2.png;ND0,ND1
sprite.Img_Roadside_90_L3=./objects/roadside/image/Img_Roadside_90_L3.png;ND0,ND1
sprite.Img_Roadside_90_L4=./objects/roadside/image/Img_Roadside_90_L4.png;ND0,ND1
sprite.Img_Roadside_90_L5=./objects/roadside/image/Img_Roadside_90_L5.png;ND0,ND1
sprite.Img_Roadside_90_L6=./objects/roadside/image/Img_Roadside_90_L6.png;ND0,ND1
sprite.Img_Roadside_90_L7=./objects/roadside/image/Img_Roadside_90_L7.png;ND0,ND1
