	INCLUDE "./Engine/Graphics/ConstantsAnimation.asm"
	INCLUDE "./generated-code/EHZ/T2/Sonic/Sonic_ImageSet.glb"
	org   $3318
	setdp $FF

* Generated Code

        fcb   $FF
SonAni_Walk 
        fdb   Img_sonic_015
        fdb   Img_sonic_016
        fdb   Img_sonic_017
        fdb   Img_sonic_018
        fdb   Img_sonic_019
        fdb   Img_sonic_020
        fdb   Img_sonic_013
        fdb   Img_sonic_014
        fcb   _resetAnim
        fcb   $FF
SonAni_Walk_1 
        fdb   Img_sonic_023
        fdb   Img_sonic_024
        fdb   Img_sonic_025
        fdb   Img_sonic_026
        fdb   Img_sonic_027
        fdb   Img_sonic_028
        fdb   Img_sonic_021
        fdb   Img_sonic_022
        fcb   _resetAnim
        fcb   $FF
SonAni_Walk_2 
        fdb   Img_sonic_031
        fdb   Img_sonic_032
        fdb   Img_sonic_033
        fdb   Img_sonic_034
        fdb   Img_sonic_035
        fdb   Img_sonic_036
        fdb   Img_sonic_029
        fdb   Img_sonic_030
        fcb   _resetAnim
        fcb   $FF
SonAni_Walk_3 
        fdb   Img_sonic_039
        fdb   Img_sonic_040
        fdb   Img_sonic_041
        fdb   Img_sonic_042
        fdb   Img_sonic_043
        fdb   Img_sonic_044
        fdb   Img_sonic_037
        fdb   Img_sonic_038
        fcb   _resetAnim
        fcb   $FF
SonAni_Run 
        fdb   Img_sonic_045
        fdb   Img_sonic_046
        fdb   Img_sonic_047
        fdb   Img_sonic_048
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   $FF
SonAni_Run_1 
        fdb   Img_sonic_049
        fdb   Img_sonic_050
        fdb   Img_sonic_051
        fdb   Img_sonic_052
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   $FF
SonAni_Run_2 
        fdb   Img_sonic_053
        fdb   Img_sonic_054
        fdb   Img_sonic_055
        fdb   Img_sonic_056
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   $FF
SonAni_Run_3 
        fdb   Img_sonic_057
        fdb   Img_sonic_058
        fdb   Img_sonic_059
        fdb   Img_sonic_060
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   $FF
SonAni_Tumble 
        fdb   Img_sonic_061
        fdb   Img_sonic_065
        fdb   Img_sonic_062
        fdb   Img_sonic_065
        fdb   Img_sonic_063
        fdb   Img_sonic_065
        fdb   Img_sonic_064
        fdb   Img_sonic_065
        fcb   _resetAnim
        fcb   $FE
SonAni_Roll 
        fdb   Img_sonic_061
        fdb   Img_sonic_065
        fdb   Img_sonic_062
        fdb   Img_sonic_065
        fdb   Img_sonic_063
        fdb   Img_sonic_065
        fdb   Img_sonic_064
        fdb   Img_sonic_065
        fcb   _resetAnim
        fcb   $FE
SonAni_Roll2 
        fdb   Img_sonic_061
        fdb   Img_sonic_065
        fdb   Img_sonic_062
        fdb   Img_sonic_065
        fdb   Img_sonic_063
        fdb   Img_sonic_065
        fdb   Img_sonic_064
        fdb   Img_sonic_065
        fcb   _resetAnim
        fcb   $FD
SonAni_Push 
        fdb   Img_sonic_072
        fdb   Img_sonic_073
        fdb   Img_sonic_074
        fdb   Img_sonic_075
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   _resetAnim
        fcb   5
SonAni_Wait 
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_001
        fdb   Img_sonic_002
        fdb   Img_sonic_003
        fdb   Img_sonic_003
        fdb   Img_sonic_003
        fdb   Img_sonic_003
        fdb   Img_sonic_003
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_004
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_005
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_006
        fdb   Img_sonic_007
        fdb   Img_sonic_008
        fdb   Img_sonic_008
        fdb   Img_sonic_008
        fdb   Img_sonic_009
        fdb   Img_sonic_009
        fdb   Img_sonic_009
        fcb   _goBackNFrames
        fcb   6
        fcb   9
SonAni_Balance 
        fdb   Img_sonic_204
        fdb   Img_sonic_205
        fdb   Img_sonic_206
        fdb   Img_sonic_205
        fcb   _resetAnim
        fcb   5
SonAni_LookUp 
        fdb   Img_sonic_011
        fdb   Img_sonic_012
        fcb   _goBackNFrames
        fcb   1
        fcb   5
SonAni_Duck 
        fdb   Img_sonic_076
        fdb   Img_sonic_077
        fcb   _goBackNFrames
        fcb   1
        fcb   0
SonAni_Spindash 
        fdb   Img_sonic_066
        fdb   Img_sonic_067
        fdb   Img_sonic_066
        fdb   Img_sonic_068
        fdb   Img_sonic_066
        fdb   Img_sonic_069
        fdb   Img_sonic_066
        fdb   Img_sonic_070
        fdb   Img_sonic_066
        fdb   Img_sonic_071
        fcb   _resetAnim
        fcb   1
SonAni_Blink 
        fdb   Img_sonic_002
        fcb   _goToAnimation
        fdb   SonAni_Walk
        fcb   3
SonAni_GetUp 
        fdb   Img_sonic_010
        fcb   _goToAnimation
        fdb   SonAni_Walk
        fcb   5
SonAni_Stop 
        fdb   Img_sonic_210
        fdb   Img_sonic_211
        fdb   Img_sonic_212
        fdb   Img_sonic_213
        fcb   _goToAnimation
        fdb   SonAni_Walk
        fcb   47
SonAni_Spring 
        fdb   Img_sonic_091
        fcb   _goToAnimation
        fdb   SonAni_Walk
        fcb   15
SonAni_Dash2 
        fdb   Img_sonic_067
        fdb   Img_sonic_067
        fdb   Img_sonic_067
        fcb   _goBackNFrames
        fcb   1
        fcb   15
SonAni_Dash3 
        fdb   Img_sonic_067
        fdb   Img_sonic_068
        fcb   _goBackNFrames
        fcb   1
        fcb   32
SonAni_DeathBW 
        fdb   Img_sonic_094
        fcb   _resetAnim
        fcb   32
SonAni_Death 
        fdb   Img_sonic_092
        fcb   _resetAnim
        fcb   64
SonAni_Hurt 
        fdb   Img_sonic_078
        fcb   _resetAnim
        fcb   9
SonAni_Slide 
        fdb   Img_sonic_078
        fdb   Img_sonic_079
        fcb   _resetAnim
        fcb   119
SonAni_Blank 
        fdb   Img_sonic_000
        fcb   _goToAnimation
        fdb   SonAni_Walk
        fcb   9
SonAni_Lying 
        fdb   Img_sonic_008
        fdb   Img_sonic_009
        fcb   _resetAnim
        fcb   3
SonAni_LieDown 
        fdb   Img_sonic_007
        fcb   _goToAnimation
        fdb   SonAni_Walk
