; -----------------------------------------------------------------------------
; Horizontal Scroll (looping 160px band)
; -----------------------------------------------------------------------------
; wide-dot - Benoit Rousseau - 07/2026
; ---------------------------------------
; - render a 160px wide band (H lines + 1 guard line above) that loops on
;   itself in x
; - band pixels are baked at build time into two code buffers (stack blast,
;   one per RAM bank), generated by png2bin -hs (6809-game-builder). The
;   generator adds a solid color guard line (png2bin -hsc) on top of the band
; - horizontal scroll is chunky 2px :
;     16px steps : entry point in code buffer (uniform bottom line chunks),
;                  exit point is fixed (jmp patched at the end of the buffer)
;      4px steps : S register offset on destination
;      2px steps : RAMA/RAMB destination swap (+1 byte on one side)
; - the whole band is redrawn each frame (constant cost, no differential).
;   Rotating the entry by h chunks skips the 4*h wrapped bytes : the hole
;   lands in the guard line and is refilled with the guard color after each
;   run, so nothing stale ever remains (irq garbage included)
; - accepted artefacts : up to 8px of spill on lines above/below the band
;   (S fine offset) and a 1px vertical shear at the wrap column (ribbon mode)
; - as S register is used to write in video buffer, an irq will write 12 bytes
;   just before the current write position. Bytes below the band start are
;   never rewritten, so place the band at the top of screen (spill then ends
;   in $9FF4-$9FFF / $BFF4-$BFFF unused areas) or over a repainted area
; -----------------------------------------------------------------------------

        opt c

; constants
; -----------------------------------------------------------------------------
hscroll.OPCODE_JMP_E        equ   $7E
hscroll.ENTRY_CHUNK_SIZE    equ   8    ; code bytes by entry line chunk (16px)

; parameters
; -----------------------------------------------------------------------------
hscroll.obj.bufferA.page    fcb   0    ; code buffer for plane 0 (RAMA data)
hscroll.obj.bufferA.address fdb   0
hscroll.obj.bufferB.page    fcb   0    ; code buffer for plane 1 (RAMB data)
hscroll.obj.bufferB.address fdb   0
hscroll.patch.offset        fdb   0    ; jmp pad location = CODE_SIZE-3 (set by _hscroll.setExitOffset)
hscroll.guard               fdb   0    ; guard color word (set by _hscroll.setGuardColor)
hscroll.camera.speed        fdb   0    ; (signed 8.8 fixed point) band shift in px/50hz
hscroll.camera.x            fdb   0    ; (8.8 fixed point) band shift, int part in [0,160)
hscroll.dest.zoneA          fdb   0    ; band end address in $C000-$DFFF video zone
hscroll.dest.zoneB          fdb   0    ; band end address in $A000-$BFFF video zone

; temporary variables in dp
; -----------------------------------------------------------------------------
hscroll.h                   equ dp_extreg    ; BYTE entry chunk index (0-9)
hscroll.w                   equ dp_extreg+1  ; BYTE 2px phase (0-1)
hscroll.bo                  equ dp_extreg+2  ; WORD S byte offset (-2..1, sign extended)
hscroll.destForA            equ dp_extreg+4  ; WORD S start for buffer A code
hscroll.destForB            equ dp_extreg+6  ; WORD S start for buffer B code
hscroll.dest.current        equ dp_extreg+8  ; WORD S start for current buffer
hscroll.loop.counter        equ dp_extreg+10 ; BYTE

; -----------------------------------------------------------------------------
; hscroll.move
; -----------------------------------------------------------------------------
; input  REG : none
; -----------------------------------------------------------------------------
; apply frame compensated speed to band position, wrap int part in [0,160)
; -----------------------------------------------------------------------------
hscroll.move
        ; check for elapsed frames
        lda   gfxlock.frameDrop.count
        bne   >
        rts
;
        ; compute frame compensated move
!       sta   <hscroll.loop.counter
        ldd   #0
!       addd  hscroll.camera.speed
        dec   <hscroll.loop.counter
        bne   <
        addd  hscroll.camera.x

        ; wrap integer part in [0,160)
        ; int part is in [0,160+126] when moving right and [-127,159] when
        ; moving left, values >= 160 (unsigned) are disambiguated by the
        ; direction (so compensated move is implicitly capped to +/-96px)
        tst   hscroll.camera.speed
        bmi   @neg
@pos    cmpa  #160                     ; unsigned compare
        blo   @end
        suba  #160
        bra   @pos
@neg    cmpa  #160                     ; negative int part shows as >= $A0
        blo   @end
        adda  #160
        bra   @neg
@end    std   hscroll.camera.x
        rts

; -----------------------------------------------------------------------------
; hscroll.do
; -----------------------------------------------------------------------------
; input  REG : none
; -----------------------------------------------------------------------------
; render the whole band at current position (to be called between
; _gfxlock.on and _gfxlock.off, writes to the back buffer)
; -----------------------------------------------------------------------------
hscroll.do
        ; decompose band shift : x = 16*h + 4*bo + 2*w
        ; h  : entry chunk in code buffer (0-9)
        ; bo : S byte offset (-2..1)
        ; w  : 2px phase, swap RAMA/RAMB destinations (0-1)
        lda   hscroll.camera.x         ; integer part (0-159)
        adda  #8
        tfr   a,b
        lsra
        lsra
        lsra
        lsra                           ; a = (x+8)/16 (0-10)
        cmpa  #10
        bne   >
        clra                           ; chunk 10 wraps to chunk 0
!       sta   <hscroll.h
        andb  #$0F
        subb  #8                       ; b = fine part (-8..7)
        tfr   b,a
        asra                           ; a = fine part / 2 (-4..3)
        tfr   a,b
        andb  #1
        stb   <hscroll.w
        asra                           ; a = S byte offset (-2..1)
        tfr   a,b
        sex
        std   <hscroll.bo

        ; compute S start address for each code buffer
        tst   <hscroll.w
        bne   @w1
        ; phase 0 : plane 0 -> $C000 zone, plane 1 -> $A000 zone
        addd  hscroll.dest.zoneA
        std   <hscroll.destForA
        ldd   <hscroll.bo
        addd  hscroll.dest.zoneB
        std   <hscroll.destForB
        bra   @run
        ; phase 1 (2px) : plane 1 -> $C000 zone (+1), plane 0 -> $A000 zone
@w1     addd  hscroll.dest.zoneA
        addd  #1
        std   <hscroll.destForB
        ldd   <hscroll.bo
        addd  hscroll.dest.zoneB
        std   <hscroll.destForA
@run
        ; run buffer B then buffer A
        ldd   <hscroll.destForB
        std   <hscroll.dest.current
        lda   hscroll.obj.bufferB.page
        ldx   hscroll.obj.bufferB.address
        bsr   hscroll.runBuffer
        ldd   <hscroll.destForA
        std   <hscroll.dest.current
        lda   hscroll.obj.bufferA.page
        ldx   hscroll.obj.bufferA.address
        ; fallthrough to hscroll.runBuffer (last call, returns to caller)

; -----------------------------------------------------------------------------
; hscroll.runBuffer
; -----------------------------------------------------------------------------
; input  REG : [a] code buffer page
; input  REG : [x] code buffer address (in cartridge space)
; input  VAR : [hscroll.dest.current] S start address
; input  VAR : [hscroll.h] entry chunk index
; -----------------------------------------------------------------------------
hscroll.runBuffer
        _SetCartPageA                  ; mount page that contain buffer code
        tfr   x,u
        ldd   hscroll.patch.offset
        leau  d,u                      ; u = jmp pad at the end of code buffer
        lda   #hscroll.OPCODE_JMP_E    ; build exit jmp instruction
        ldy   #@ret
        sta   ,u
        sty   1,u
        ldb   <hscroll.h
        lda   #hscroll.ENTRY_CHUNK_SIZE
        mul                            ; d = h * chunk size
        leax  d,x                      ; x = entry point in code buffer
        sts   @save_s
        lds   <hscroll.dest.current
        jmp   ,x
@ret    tfr   s,u                      ; u = end of the unwritten hole (4*h bytes)
        lds   #0
@save_s equ   *-2
        ; refill the hole with the guard color (erases stale data and
        ; irq garbage left in the skipped area of the guard line)
        ldb   <hscroll.h
        beq   @end
        ldx   hscroll.guard
        tfr   x,y
!       pshu  x,y                      ; 4 bytes by iteration (one entry chunk)
        decb
        bne   <
@end    rts
