engine.asm.mainEngine=./game-mode/tailtest/main.asm

# Objects - ordered by id from 1 to n
object.tailmgr=./objects/tailmgr/tailmgr.properties

# Palettes
palette.Pal_0=./objects/sprite/images/1.png

# Acts definition
actBoot=tailtest

act.tailtest.palette=Pal_0
act.tailtest.screenBorder=0
act.tailtest.backgroundSolid=0
