engine.asm.mainEngine=./game-mode/01/main.asm

# Palettes
palette.Pal_game=./game-mode/01/images/pal.png
palette.Pal_tunnel=./game-mode/01/images/pal-inside.png
palette.Pal_black=../../engine/palette/color/Pal_black.png
palette.Pal_messages=./objects/messages/images/messages.png
object.fade=../../engine/objects/palette/fade/fade.properties

# Animation
object.animation=./objects/animation/obj.t2.properties

# Main Objects
object.LevelInit=./objects/levels/01/obj.t2.properties
object.LevelWave=./objects/levels/01/object-wave/obj.t2.properties
object.Mask=./objects/levels/mask/mask.t2.properties
object.hud=./objects/levels/hud/hud.t2.properties
object.fadetotunnel=./objects/levels/01/background/obj_fadetotunnel.t2.properties
object.collision=./objects/collision/01.t2.properties
object.createFoeFire=./global/objects/createFoeFire.properties
object.loadFirePreset=./global/objects/loadFirePreset.properties
object.messages=./objects/messages/obj.t2.properties
object.checkpoint=./objects/checkpoint/checkpoint.t2.properties

# Music and snd
#object.vgc01=./objects/levels/01/music/vgc.properties
object.ymm01=./objects/levels/01/music/ymm.t2.properties
object.bossmusic=./objects/levels/bossmusic/obj_bossmusic.t2.properties
object.soundFX=./objects/soundFX/soundFX.t2.properties

# Level 1 Specific
object.initlevel1=./objects/player1/initlevel1/obj.t2.properties
object.engineflames=./objects/player1/engineflames/obj.t2.properties

# Player 1 Objects
object.Player1=./objects/player1/player1.t2.properties
object.Weapon=./objects/player1/weapon/obj.t2.properties
object.bitdevice=./objects/player1/bitdevice/obj.t2.properties
object.beamcharge=./objects/player1/beam/beamcharge.t2.properties
object.beamp=./objects/player1/beam/beam.t2.properties
object.pow=./objects/player1/pow/pow.t2.properties
object.pow_optionbox=./objects/player1/pow/pow_optionbox.t2.properties
object.forcepod=./objects/player1/forcepods/forcepod.t2.properties
object.forcepod_simplefire=./objects/player1/forcepods/obj_simplefire.t2.properties
object.forcepod_reboundlaser=./objects/player1/forcepods/obj_reboundlaser.t2.properties
object.forcepod_counterairlaser=./objects/player1/forcepods/obj_counterairlaser.t2.properties
object.commonmissile=./objects/foefire/obj_commonmissile.t2.properties
object.commonmissileflame=./objects/foefire/obj_commonmissileflame.t2.properties

# Enemies Objects
object.patapata=./objects/enemies/pata-pata/obj.t2.properties
object.bug=./objects/enemies/bug/obj_level1.t2.properties
object.scant=./objects/enemies/scant/obj.t2.properties
object.scantfire=./objects/foefire/obj_scantfire.t2.properties
object.tabrok=./objects/enemies/tabrok/obj.t2.properties
object.tabrokcanon=./objects/foefire/obj_tabrokcanon.t2.properties
object.pstaff=./objects/enemies/p-staff/obj.t2.properties
object.bink=./objects/enemies/bink/obj.t2.properties
object.shell=./objects/enemies/shell/obj.t2.properties
object.shellmask=./objects/enemies/shell/mask.t2.properties
object.missileflame=./objects/foefire/obj_commonmissileflame.t2.properties
object.blaster=./objects/enemies/blaster/obj.t2.properties
object.cancer=./objects/enemies/cancer/obj.t2.properties
object.dobkeratops=./objects/enemies/dobkeratops/obj.t2.properties
object.dobkeratops_jaw=./objects/enemies/dobkeratops/jaw.t2.properties
object.dobkeratops_tail=./objects/enemies/dobkeratops/tail.t2.properties
object.dobkeratops_monster=./objects/enemies/dobkeratops/monster.t2.properties
object.dobkeratops_saw=./objects/enemies/dobkeratops/saw.t2.properties

# Explosion
object.explosion=./objects/explosion/obj.t2.properties

# Foe Fires
object.foefire=./objects/foefire/obj.t2.properties
object.emitter_flash=./objects/foefire/obj_emitter-flash.t2.properties

# Acts definition
actBoot=default
act.default.palette=Pal_black
act.default.screenBorder=0
act.default.backgroundSolid=0
