engine.asm.mainEngine=./game-mode/bandscroll/main.asm

# Palettes / Acts definition
palette.Pal_0=./objects/band/band.png
actBoot=main
act.main.palette=Pal_0
act.main.screenBorder=0
act.main.backgroundSolid=0

# Objects
# -------------------------------------
# hscroll code buffers (pure code/data, never spawned)
object.bandA=./objects/band/bandA.properties
object.bandB=./objects/band/bandB.properties
