engine.asm.mainEngine=./game-mode/fadetest/main.asm

# Palette (reprise de l'ecran de chargement : couleur 0 = noir, 15 != noir)
palette.Pal_game=./objects/levels/loading/images/loading.png

# Acts definition
actBoot=default
act.default.palette=Pal_game
act.default.screenBorder=0
act.default.backgroundSolid=0
