        INCLUDE "./engine/graphics/sprite/background-erase-mode/DisplaySprite.asm"	
        INCLUDE "./engine/graphics/sprite/background-erase-mode/CheckSpritesRefresh.asm"
        INCLUDE "./engine/graphics/sprite/background-erase-mode/EraseSprites.asm"
        INCLUDE "./engine/graphics/sprite/background-erase-mode/UnsetDisplayPriority.asm"
        INCLUDE "./engine/graphics/sprite/background-erase-mode/DrawSpritesExtEnc.asm"
        INCLUDE "./engine/graphics/sprite/background-erase-mode/BgBufferAlloc.asm"	
        INCLUDE "./engine/graphics/sprite/background-erase-mode/DeleteObject.asm"