# ******************************************************************************
# BuildDisk - Configuration file (macOS)
# road-generator : démo route en perspective avec rasters de palette
# ******************************************************************************

# Engine ASM source code (loader)
# ******************************************************************************
engine.asm.boot.fd=../../engine/boot/boot-fd.asm
engine.asm.RAMLoaderManager.fd=../../engine/ram/RAMLoaderManagerFd.asm
engine.asm.RAMLoader.fd=../../engine/ram/zx0/RAMLoaderFd.asm

engine.asm.boot.t2=../../engine/boot/boot-t2.asm
engine.asm.RAMLoaderManager.t2=../../engine/ram/RAMLoaderManagerT2.asm
engine.asm.RAMLoader.t2=../../engine/ram/zx0/RAMLoaderT2.asm

engine.asm.boot.t2flash=../../engine/boot/boot-t2-flash.asm
engine.asm.t2flash=../../engine/megarom-t2/t2-flash.asm

# Game definition
# ******************************************************************************
gameModeBoot=road
gameMode.road=./game-mode/road/main.properties

# Build parameters (LWASM)
# ******************************************************************************
builder.lwasm=../../tools/macos/lwasm
builder.lwasm.pragma=undefextern
builder.lwasm.includeDirs=../..,.
builder.lwasm.define=

# Build parameters (générique)
# ******************************************************************************
builder.debug=Y
builder.logToConsole=Y
builder.parallel=Y
builder.diskName=./dist/road-generator
builder.t2Name=road-generator
builder.generatedCode=./generated-code
builder.constAnim=./engine/graphics/animation/constants-animation.equ
builder.to8.memoryExtension=Y
builder.compilatedSprite.useCache=Y
builder.compilatedSprite.maxTries=500000
