#!/usr/bin/env python3
"""Emit the star-cluster offset patterns -> global/clusters.asm.

A cluster is one master star plus 6 satellites at FIXED offsets. Only the master
has a position; the satellites are derived every frame from its address, which is
what makes them nearly free.

WHY dx MUST BE A MULTIPLE OF 4 -- this is the whole optimisation, and this script
exists to enforce it. BM16 addressing is:
    byte  = y*40 + (x>>2)
    plane = RAM B ($A000) if (x AND 2) else RAM A ($C000)
    nibble= low if (x AND 1) else high
For a satellite at (x+dx, y+dy) with dx a multiple of 4:
    (x+dx)>>2  == (x>>2) + dx/4     exact: no carry out of the low 2 bits
    (x+dx) AND 2 == x AND 2         SAME PLANE
    (x+dx) AND 1 == x AND 1         SAME NIBBLE
so the satellite sits at master_addr + (dy*40 + dx/4) -- a CONSTANT delta -- and
shares the master's plane and nibble mask.

With an arbitrary dx the plane and nibble depend on the master's live x, which
changes every frame, so each satellite would need the full address computation and
there would be no saving at all. dx ≡ 2 (mod 4) is not enough either: it keeps the
nibble but FLIPS the plane, and the direction of the flip depends on the master's
current (x AND 2), so the delta stops being constant.

dy is unconstrained: it only scales y*40. DX_MAX/DY_MAX are chosen for LOOKS: a
BM16 pixel is twice as wide as it is tall and dx is stuck on a 4px grid, so
|dx|<=28 spans 56 px = 112 SCREEN units and |dy|<=28 spans 57, so a cluster covers
roughly a third of the screen. At that spread the members barely read as a group
at all, which is the point: tighter bounds (8/6, then 20/20) read as clumps.

More patterns are needed as N_MEMBER falls: with only 4 members a pattern is much
less distinctive, so 8 of them keep the sky from repeating.

The bounds are not free: they are what lets the render skip the per-member clip
test whenever the master is away from the screen edges. Widening them widens the
slow-path band, so keep them in sync with starfield.asm's fast-path test.

There is NO vertical clamp on a master's spawn y. An earlier version clamped y to
[DY_MAX, 199-DY_MAX] so a cluster could never leave the screen vertically and no
member ever needed a y test. That is fine while DY_MAX is small, but it starves
the screen edges as it grows: with |dy|<=20 a clamp to [20,179] leaves row 0
reachable only by a master at exactly y=20 with dy=-20, so rows 0..40 ramp from
~4% density to full -- a bald band over a fifth of the screen. Clipping members
vertically instead keeps master density uniform over all 200 rows.
"""
import math
import os
import random

N_PAT = 8                    # patterns, one drawn per master at spawn
N_MEMBER = 4                 # master + 3 satellites
DX_MAX = 28                  # keep in sync with the fast-path test in starfield.asm
DY_MAX = 28                  # keep in sync with the fast-path test in starfield.asm
ROW = 40                     # bytes per scanline per bank

MIN_SEP = 14                 # minimum distance between members, SCREEN units
SEED = 20260715              # fixed: the patterns must not change between builds


def sep(a, b):
    """Distance between two members in SCREEN units.

    A BM16 pixel is twice as wide as it is tall, so dx counts double. Comparing
    raw (dx,dy) instead would call a pair 4 px apart "distant" when on screen
    they are 8 units apart and read as one smeared star.
    """
    return math.hypot(2 * (a[0] - b[0]), a[1] - b[1])


def make_pattern(rng):
    """-> [(dx, dy)] of length N_MEMBER, master at (0,0) first, well separated.

    MIN_SEP is why this loop exists. Rejecting only EXACT duplicates is not
    enough: it let through pairs 3 screen units apart, which do not read as two
    stars but as ONE star with a ghost trailing it -- worst on the fast layer,
    where the pair sweeps past quickest. A star is 2 screen units wide, so
    members need real space between them, not merely different pixels.
    """
    dx_choices = [d for d in range(-DX_MAX, DX_MAX + 1, 4)]
    out = [(0, 0)]
    guard = 0
    while len(out) < N_MEMBER:
        guard += 1
        if guard > 10000:                      # MIN_SEP too big for the box
            raise SystemExit(f"cannot place {N_MEMBER} members {MIN_SEP} apart "
                             f"within dx+-{DX_MAX} dy+-{DY_MAX}")
        p = (rng.choice(dx_choices), rng.randint(-DY_MAX, DY_MAX))
        if all(sep(p, q) >= MIN_SEP for q in out):
            out.append(p)
    return out


def main():
    rng = random.Random(SEED)
    pats = [make_pattern(rng) for _ in range(N_PAT)]

    L = []
    L.append("* ==========================================================================")
    L.append("* clusters.asm — GENERATED by tools/gen-clusters.py, do not hand-edit.")
    L.append("* --------------------------------------------------------------------------")
    L.append(f"* {N_PAT} cluster patterns of {N_MEMBER} members (master + {N_MEMBER-1} satellites).")
    L.append("*")
    L.append("* Every dx is a multiple of 4. That is not cosmetic: it is the reason a")
    L.append("* satellite's VRAM address is master_addr + a CONSTANT delta, sharing the")
    L.append("* master's plane and nibble. See the header of tools/gen-clusters.py.")
    L.append("*")
    L.append(f"* |dx| <= {DX_MAX} and |dy| <= {DY_MAX}, which is what lets starfield.asm skip the")
    L.append(f"* per-member clip test when the master is at {DX_MAX} <= x <= {159-DX_MAX}, and clamp a")
    L.append(f"* master's spawn y to [{DY_MAX}, {199-DY_MAX}] so a cluster never leaves the screen")
    L.append("* vertically at all.")
    L.append("*")
    L.append("* Per member: fdb delta (dy*40 + dx/4), fdb dx sign-extended, fdb dy*40.")
    L.append("* dx and dy*40 are for the clip test: the render adds them to the master's x and")
    L.append("* cached row to decide whether this member is on screen at all.")
    L.append("* The master is member 0 at delta 0, so the render loop needs no special case.")
    L.append("* ==========================================================================")
    L.append("")
    L.append(f"CL_PATS    equ {N_PAT}")
    L.append(f"CL_MEMBERS equ {N_MEMBER}")
    L.append(f"CL_DX_MAX  equ {DX_MAX}")
    L.append(f"CL_DY_MAX  equ {DY_MAX}")
    L.append(f"CL_MEMSIZE equ 6                 ; fdb delta + fdb dx16 + fdb dyrow")
    L.append(f"CL_PATSIZE equ {N_MEMBER*6}                ; bytes per pattern")
    L.append("")
    L.append("cluster_pat")
    for i, p in enumerate(pats):
        art = render(p)
        L.append(f"* --- pattern {i} ---")
        for line in art:
            L.append(f"*   {line}")
        for dx, dy in p:
            delta = dy * ROW + dx // 4
            L.append(f"        fdb   {delta}")
            L.append(f"        fdb   {dx}")
            L.append(f"        fdb   {dy*ROW}")
        L.append("")

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "global", "clusters.asm")
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", os.path.normpath(out))
    for i, p in enumerate(pats):
        print(f"pattern {i}: {p}")
        for line in render(p):
            print("   ", line)


def render(p):
    """Crude ascii view of a pattern, master shown as M."""
    xs = [dx for dx, _ in p]
    ys = [dy for _, dy in p]
    rows = []
    for y in range(min(ys), max(ys) + 1):
        row = ""
        for x in range(min(xs), max(xs) + 1):
            if (x, y) == (0, 0):
                row += "M"
            elif (x, y) in p:
                row += "*"
            else:
                row += "."
        rows.append(row)
    return rows


if __name__ == "__main__":
    main()
