#!/usr/bin/env python3
"""Emit the 64-step orbit table -> global/orbit.asm.

The 6809 has no sine, and everything the draw/restore loops need is a pure
function of the step, so it is all precomputed here: nothing is derived at
runtime but an index.

Geometry (see docs/superpowers/specs/2026-07-14-starfield-orbiting-balls-design.md):
the alien is 40x80 px = an 80x80 SCREEN-unit square, so an enclosing circle would
need radius ~57 and would run off the bottom of the 200-row screen. The orbit is
therefore tight (radius 40 screen units), touching the alien's edge midpoints and
passing over its corners.

rx:ry is 1:2 because a BM16 pixel is twice as wide as it is tall -- that is what
makes this render as a circle instead of an ellipse.

Each entry, per step:
    fdb  vram   ; by*40 + (bx>>2)      -- add $C000 (RAM A) or $A000 (RAM B)
    fdb  buf    ; (by-ROW0)*2*NCOL + (bx>>2) - COL0  -- offset into the snapshot
    fcb  shift  ; bx AND 3             -- selects the pre-shifted sprite variant
"""
import math
import os

N = 64                 # steps per revolution; 8 balls sit N/8 = 8 steps apart
CX, CY = 80, 151       # orbit centre, BM16 pixels
RX, RY = 20, 40        # 1:2 -> circular on screen
BW, BH = 4, 8          # ball size


def positions():
    """-> [(bx, by)] top-left of the ball at each step."""
    out = []
    for i in range(N):
        a = 2 * math.pi * i / N
        out.append((CX + round(RX * math.cos(a)) - BW // 2,
                    CY + round(RY * math.sin(a)) - BH // 2))
    return out


def main():
    pos = positions()
    col0 = min(bx >> 2 for bx, _ in pos)
    col1 = max((bx + BW - 1) >> 2 for bx, _ in pos)
    ncol = col1 - col0 + 1
    row0 = min(by for _, by in pos)
    row1 = max(by for _, by in pos) + BH - 1
    nrow = row1 - row0 + 1
    plane = ncol * nrow

    assert row0 >= 0 and row1 <= 199, f"orbit off screen: rows {row0}..{row1}"

    L = []
    L.append("* ==========================================================================")
    L.append("* orbit.asm — GENERATED by tools/gen-orbit.py, do not hand-edit.")
    L.append("* --------------------------------------------------------------------------")
    L.append(f"* {N} steps per revolution, 8 balls {N//8} steps apart.")
    L.append(f"* Centre ({CX},{CY}), rx={RX} ry={RY}. The 1:2 ratio is what makes a BM16")
    L.append("* screen show this as a circle: a pixel is twice as wide as it is tall.")
    L.append(f"* Ball top-left sweeps x {min(bx for bx,_ in pos)}..{max(bx for bx,_ in pos)}"
             f"  y {row0}..{max(by for _,by in pos)}")
    L.append(f"* Covered area: byte columns {col0}..{col1} ({ncol}), rows {row0}..{row1} ({nrow}).")
    L.append("* ==========================================================================")
    L.append("")
    L.append(f"ORB_STEPS equ {N}")
    L.append(f"ORB_COL0  equ {col0}")
    L.append(f"ORB_NCOL  equ {ncol}")
    L.append(f"ORB_ROW0  equ {row0}")
    L.append(f"ORB_NROW  equ {nrow}")
    L.append(f"ORB_PLANE equ {plane}          ; bytes per bank (snapshot total = 2x this)")
    L.append("* Snapshot layout is [row][plane][col], NOT [plane][row][col]: the RAM B half of")
    L.append(f"* a row sits at +ORB_NCOL ({ncol}), a 5-bit index, where a whole-plane offset")
    L.append(f"* ({plane}) would force a 16-bit one and cost 4 extra cycles on every read.")
    L.append(f"ORB_ROWSTEP equ {2*ncol}         ; bytes per annulus row (both planes)")
    L.append("")
    L.append("* per step: fdb vram offset, fdb snapshot offset, fcb shift")
    L.append("ORB_ENTRY equ 5")
    L.append("orbit_table")
    for i, (bx, by) in enumerate(pos):
        vram = by * 40 + (bx >> 2)
        buf = (by - row0) * 2 * ncol + ((bx >> 2) - col0)
        L.append(f"        fdb   {vram}")
        L.append(f"        fdb   {buf}")
        L.append(f"        fcb   {bx & 3}         ; step {i:2d}: x={bx} y={by}")

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "..", "global", "orbit.asm")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", os.path.normpath(out))
    print(f"cols {col0}..{col1} ({ncol})  rows {row0}..{row1} ({nrow})")
    print(f"snapshot = {plane*2} bytes   table = {N*5} bytes")


if __name__ == "__main__":
    main()
