code=./objects/road/road.asm

# Sprite — road en mode Draw seul (pas de backup de fond car c'est notre fond)
# Position 0 et 1 pour permettre le shift 1 pixel si besoin
sprite.Img_Road=./objects/road/image/road.png;ND0

# Animation single-frame (sprite statique)
animation.Ani_Road=0;Img_Road;_resetAnim
