* ==========================================================================
* ball-sprites.asm — GENERATED by tools/gen-ball.py, do not hand-edit.
* --------------------------------------------------------------------------
* A 4x8 lit sphere (square on screen: a BM16 pixel is 2x wider than tall),
* in four pre-shifted variants because one BM16 byte column spans 4 px and a
* sprite cannot sit off that grid without one compiled routine per x AND 3.
*
* In:  U = $C000 + by*40 + (bx>>2)   (RAM A byte of the ball's top-left column)
* RAM B is reached at -$2000. Clobbers A only.
*
* Colours are BORROWED from the full palette (2, 9, 11, 4, 5, 6): the nebula,
* the title, the by-FX line and the stars already own all 16 slots, so the ball
* claims none. The shadow end is blue (2, 9) rather than colour 0, because 0 is
* the background: a correctly-unlit side would make the ball's bottom vanish.
* Using the star colours 4/5/6 is safe ONLY because BallsRestore wipes every
* ball pixel before StarfieldRender's 'nibble in 4..6 means star' test runs.
*
* Shape (. blue-2  - blue-9  : 143  o 158  O 219  @ 255):
*  Oo 
* OOo.
* O@o.
* OO:.
* oo-.
* --..
* ....
*  .. 
* ==========================================================================

ball_routines
        fdb   ball_draw_0
        fdb   ball_draw_1
        fdb   ball_draw_2
        fdb   ball_draw_3

* --- shift 0: ball at bx where (bx AND 3) == 0 ---
ball_draw_0
        lda   0,u
        anda  #$F0
        ora   #$05
        sta   0,u
        lda   #$55
        sta   40,u
        lda   #$56
        sta   80,u
        lda   #$55
        sta   120,u
        lda   #$44
        sta   160,u
        lda   #$99
        sta   200,u
        lda   #$22
        sta   240,u
        lda   280,u
        anda  #$F0
        ora   #$02
        sta   280,u
        lda   -8192,u
        anda  #$0F
        ora   #$40
        sta   -8192,u
        lda   #$42
        sta   -8152,u
        lda   #$42
        sta   -8112,u
        lda   #$B2
        sta   -8072,u
        lda   #$92
        sta   -8032,u
        lda   #$22
        sta   -7992,u
        lda   #$22
        sta   -7952,u
        lda   -7912,u
        anda  #$0F
        ora   #$20
        sta   -7912,u
        rts

* --- shift 1: ball at bx where (bx AND 3) == 1 ---
ball_draw_1
        lda   40,u
        anda  #$F0
        ora   #$05
        sta   40,u
        lda   41,u
        anda  #$0F
        ora   #$20
        sta   41,u
        lda   80,u
        anda  #$F0
        ora   #$05
        sta   80,u
        lda   81,u
        anda  #$0F
        ora   #$20
        sta   81,u
        lda   120,u
        anda  #$F0
        ora   #$05
        sta   120,u
        lda   121,u
        anda  #$0F
        ora   #$20
        sta   121,u
        lda   160,u
        anda  #$F0
        ora   #$04
        sta   160,u
        lda   161,u
        anda  #$0F
        ora   #$20
        sta   161,u
        lda   200,u
        anda  #$F0
        ora   #$09
        sta   200,u
        lda   201,u
        anda  #$0F
        ora   #$20
        sta   201,u
        lda   240,u
        anda  #$F0
        ora   #$02
        sta   240,u
        lda   241,u
        anda  #$0F
        ora   #$20
        sta   241,u
        lda   #$54
        sta   -8192,u
        lda   #$54
        sta   -8152,u
        lda   #$64
        sta   -8112,u
        lda   #$5B
        sta   -8072,u
        lda   #$49
        sta   -8032,u
        lda   #$92
        sta   -7992,u
        lda   #$22
        sta   -7952,u
        lda   #$22
        sta   -7912,u
        rts

* --- shift 2: ball at bx where (bx AND 3) == 2 ---
ball_draw_2
        lda   1,u
        anda  #$0F
        ora   #$40
        sta   1,u
        lda   #$42
        sta   41,u
        lda   #$42
        sta   81,u
        lda   #$B2
        sta   121,u
        lda   #$92
        sta   161,u
        lda   #$22
        sta   201,u
        lda   #$22
        sta   241,u
        lda   281,u
        anda  #$0F
        ora   #$20
        sta   281,u
        lda   -8192,u
        anda  #$F0
        ora   #$05
        sta   -8192,u
        lda   #$55
        sta   -8152,u
        lda   #$56
        sta   -8112,u
        lda   #$55
        sta   -8072,u
        lda   #$44
        sta   -8032,u
        lda   #$99
        sta   -7992,u
        lda   #$22
        sta   -7952,u
        lda   -7912,u
        anda  #$F0
        ora   #$02
        sta   -7912,u
        rts

* --- shift 3: ball at bx where (bx AND 3) == 3 ---
ball_draw_3
        lda   #$54
        sta   1,u
        lda   #$54
        sta   41,u
        lda   #$64
        sta   81,u
        lda   #$5B
        sta   121,u
        lda   #$49
        sta   161,u
        lda   #$92
        sta   201,u
        lda   #$22
        sta   241,u
        lda   #$22
        sta   281,u
        lda   -8152,u
        anda  #$F0
        ora   #$05
        sta   -8152,u
        lda   -8151,u
        anda  #$0F
        ora   #$20
        sta   -8151,u
        lda   -8112,u
        anda  #$F0
        ora   #$05
        sta   -8112,u
        lda   -8111,u
        anda  #$0F
        ora   #$20
        sta   -8111,u
        lda   -8072,u
        anda  #$F0
        ora   #$05
        sta   -8072,u
        lda   -8071,u
        anda  #$0F
        ora   #$20
        sta   -8071,u
        lda   -8032,u
        anda  #$F0
        ora   #$04
        sta   -8032,u
        lda   -8031,u
        anda  #$0F
        ora   #$20
        sta   -8031,u
        lda   -7992,u
        anda  #$F0
        ora   #$09
        sta   -7992,u
        lda   -7991,u
        anda  #$0F
        ora   #$20
        sta   -7991,u
        lda   -7952,u
        anda  #$F0
        ora   #$02
        sta   -7952,u
        lda   -7951,u
        anda  #$0F
        ora   #$20
        sta   -7951,u
        rts

