* ==========================================================================
* orbit.asm — GENERATED by tools/gen-orbit.py, do not hand-edit.
* --------------------------------------------------------------------------
* 64 steps per revolution, 8 balls 8 steps apart.
* Centre (80,151), rx=20 ry=40. The 1:2 ratio is what makes a BM16
* screen show this as a circle: a pixel is twice as wide as it is tall.
* Ball top-left sweeps x 58..98  y 107..187
* Covered area: byte columns 14..25 (12), rows 107..194 (88).
* ==========================================================================

ORB_STEPS equ 64
ORB_COL0  equ 14
ORB_NCOL  equ 12
ORB_ROW0  equ 107
ORB_NROW  equ 88
ORB_PLANE equ 1056          ; bytes per bank (snapshot total = 2x this)
* Snapshot layout is [row][plane][col], NOT [plane][row][col]: the RAM B half of
* a row sits at +ORB_NCOL (12), a 5-bit index, where a whole-plane offset
* (1056) would force a 16-bit one and cost 4 extra cycles on every read.
ORB_ROWSTEP equ 24         ; bytes per annulus row (both planes)

* per step: fdb vram offset, fdb snapshot offset, fcb shift
ORB_ENTRY equ 5
orbit_table
        fdb   5904
        fdb   970
        fcb   2         ; step  0: x=98 y=147
        fdb   6064
        fdb   1066
        fcb   2         ; step  1: x=98 y=151
        fdb   6224
        fdb   1162
        fcb   2         ; step  2: x=98 y=155
        fdb   6384
        fdb   1258
        fcb   1         ; step  3: x=97 y=159
        fdb   6504
        fdb   1330
        fcb   0         ; step  4: x=96 y=162
        fdb   6664
        fdb   1426
        fcb   0         ; step  5: x=96 y=166
        fdb   6783
        fdb   1497
        fcb   3         ; step  6: x=95 y=169
        fdb   6903
        fdb   1569
        fcb   1         ; step  7: x=93 y=172
        fdb   7023
        fdb   1641
        fcb   0         ; step  8: x=92 y=175
        fdb   7142
        fdb   1712
        fcb   3         ; step  9: x=91 y=178
        fdb   7222
        fdb   1760
        fcb   1         ; step 10: x=89 y=180
        fdb   7301
        fdb   1807
        fcb   3         ; step 11: x=87 y=182
        fdb   7381
        fdb   1855
        fcb   2         ; step 12: x=86 y=184
        fdb   7421
        fdb   1879
        fcb   0         ; step 13: x=84 y=185
        fdb   7460
        fdb   1902
        fcb   2         ; step 14: x=82 y=186
        fdb   7500
        fdb   1926
        fcb   0         ; step 15: x=80 y=187
        fdb   7499
        fdb   1925
        fcb   2         ; step 16: x=78 y=187
        fdb   7499
        fdb   1925
        fcb   0         ; step 17: x=76 y=187
        fdb   7458
        fdb   1900
        fcb   2         ; step 18: x=74 y=186
        fdb   7418
        fdb   1876
        fcb   0         ; step 19: x=72 y=185
        fdb   7377
        fdb   1851
        fcb   2         ; step 20: x=70 y=184
        fdb   7297
        fdb   1803
        fcb   1         ; step 21: x=69 y=182
        fdb   7216
        fdb   1754
        fcb   3         ; step 22: x=67 y=180
        fdb   7136
        fdb   1706
        fcb   1         ; step 23: x=65 y=178
        fdb   7016
        fdb   1634
        fcb   0         ; step 24: x=64 y=175
        fdb   6895
        fdb   1561
        fcb   3         ; step 25: x=63 y=172
        fdb   6775
        fdb   1489
        fcb   1         ; step 26: x=61 y=169
        fdb   6655
        fdb   1417
        fcb   0         ; step 27: x=60 y=166
        fdb   6495
        fdb   1321
        fcb   0         ; step 28: x=60 y=162
        fdb   6374
        fdb   1248
        fcb   3         ; step 29: x=59 y=159
        fdb   6214
        fdb   1152
        fcb   2         ; step 30: x=58 y=155
        fdb   6054
        fdb   1056
        fcb   2         ; step 31: x=58 y=151
        fdb   5894
        fdb   960
        fcb   2         ; step 32: x=58 y=147
        fdb   5734
        fdb   864
        fcb   2         ; step 33: x=58 y=143
        fdb   5574
        fdb   768
        fcb   2         ; step 34: x=58 y=139
        fdb   5414
        fdb   672
        fcb   3         ; step 35: x=59 y=135
        fdb   5295
        fdb   601
        fcb   0         ; step 36: x=60 y=132
        fdb   5135
        fdb   505
        fcb   0         ; step 37: x=60 y=128
        fdb   5015
        fdb   433
        fcb   1         ; step 38: x=61 y=125
        fdb   4895
        fdb   361
        fcb   3         ; step 39: x=63 y=122
        fdb   4776
        fdb   290
        fcb   0         ; step 40: x=64 y=119
        fdb   4656
        fdb   218
        fcb   1         ; step 41: x=65 y=116
        fdb   4576
        fdb   170
        fcb   3         ; step 42: x=67 y=114
        fdb   4497
        fdb   123
        fcb   1         ; step 43: x=69 y=112
        fdb   4417
        fdb   75
        fcb   2         ; step 44: x=70 y=110
        fdb   4378
        fdb   52
        fcb   0         ; step 45: x=72 y=109
        fdb   4338
        fdb   28
        fcb   2         ; step 46: x=74 y=108
        fdb   4299
        fdb   5
        fcb   0         ; step 47: x=76 y=107
        fdb   4299
        fdb   5
        fcb   2         ; step 48: x=78 y=107
        fdb   4300
        fdb   6
        fcb   0         ; step 49: x=80 y=107
        fdb   4340
        fdb   30
        fcb   2         ; step 50: x=82 y=108
        fdb   4381
        fdb   55
        fcb   0         ; step 51: x=84 y=109
        fdb   4421
        fdb   79
        fcb   2         ; step 52: x=86 y=110
        fdb   4501
        fdb   127
        fcb   3         ; step 53: x=87 y=112
        fdb   4582
        fdb   176
        fcb   1         ; step 54: x=89 y=114
        fdb   4662
        fdb   224
        fcb   3         ; step 55: x=91 y=116
        fdb   4783
        fdb   297
        fcb   0         ; step 56: x=92 y=119
        fdb   4903
        fdb   369
        fcb   1         ; step 57: x=93 y=122
        fdb   5023
        fdb   441
        fcb   3         ; step 58: x=95 y=125
        fdb   5144
        fdb   514
        fcb   0         ; step 59: x=96 y=128
        fdb   5304
        fdb   610
        fcb   0         ; step 60: x=96 y=132
        fdb   5424
        fdb   682
        fcb   1         ; step 61: x=97 y=135
        fdb   5584
        fdb   778
        fcb   2         ; step 62: x=98 y=139
        fdb   5744
        fdb   874
        fcb   2         ; step 63: x=98 y=143
