code=./objects/player1/forcepods/obj_simplefire.asm
# Sprites
sprite.Img_shootup=./objects/player1/forcepods/images/shootpod_0.png;NB0
sprite.Img_shootupright=./objects/player1/forcepods/images/shootpod_1.png;NB0
sprite.Img_shootright=./objects/player1/forcepods/images/shootpod_2.png;NB0
sprite.Img_shootdownright=./objects/player1/forcepods/images/shootpod_3.png;NB0
sprite.Img_shootdown=./objects/player1/forcepods/images/shootpod_4.png;NB0

# TODO those are duplicates see player1/weapon object !!!
sprite.Img_weapon_impact0=./objects/player1/weapon/images/impact-0.png;NB0
sprite.Img_weapon_impact3=./objects/player1/weapon/images/impact-3.png;NB0
