 IFNDEF GLOBAL_VARIABLES

GLOBAL_VARIABLES EQU $9DF0

PALETTE_FADER EQU GLOBAL_VARIABLES+0 ; 2 bytes
NEXT_GAME_MODE_PRESENT EQU GLOBAL_VARIABLES+2 ; 1 byte
NEXT_GAME_MODE EQU GLOBAL_VARIABLES+3 ; 1 byte

 ENDC
