 IFNDEF GLOBAL_EQUATES
GLOBAL_EQUATES EQU 1
* Graphics
XY_CENTERED_FULL_IMAGE 	EQU $807F 
LAYER_BACKGROUND       	EQU 7 
OUT_OF_SYNC_VBL 	EQU 255
MUSIC_LOOP 		EQU 1
NO_CALLBACK             EQU $0000
 ENDC